name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm install
        working-directory: ./PROJECT-DEVOPS  # Specify the directory where package.json is located

      - name: Build React app
        run: npm run build
        working-directory: ./PROJECT-DEVOPS  # Specify the directory where package.json is located

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        working-directory: ./PROJECT-DEVOPS/build  # Specify the directory where the build artifacts are located
